PUT http://localhost:3001/api/notes/681dee0f760292626103cef7
Content-Type: application/json

{
    "content": "you have to add try/catch to handle errors with async/await method",
    "important": true
}